robotics/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import List, Simple, Coordinated

app_name = 'robotics'
# handler404 = 'show_404'

urlpatterns = [

    url(r'^$', TemplateView.as_view(template_name="robotics/base.html"), name='home'),
    url(r'^about-us/$', TemplateView.as_view(template_name="robotics/about-us.html"), name='about-us'),
    url(r'^contact-us/$', TemplateView.as_view(template_name="robotics/contact-us.html"), name='contact-us'),
    url(r'^control/$', TemplateView.as_view(template_name="robotics/control.html"), name='control'),

    
    url(r'^control/simple/$', Simple.as_view(
            template_name="robotics/fingers.html",
            # success_url= '/control/simple/',
        ), name='simple'),
    
    url(r'^control/coordinated/$', Coordinated.as_view(
            template_name="robotics/all_fingers.html",
            # success_url= '/control/coordinated/',
        ), name='all-fingers'),
    url(r'^list/', List.as_view(template_name="robotics/requests.html"), name='list'),   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartrobot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('robotics.urls', namespace='robotics')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

robotics/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User, AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator


SIMPLE_CHOICES = (
	
            ('Thumb finger', 'Thumb finger'),
            ('Index finger', 'Index finger'),
            ('Middle finger', 'Middle finger'),
            ('Ring finder', 'Ring finder'),
            ('Little finger', 'Little finger'),
	)

COORDINATED_CHOICES = (
			('Take', 'Take'),
			('Let go', 'Let go'),
			('Move', 'Move'),
	)


@python_2_unicode_compatible
class SimpleMovement(models.Model):
	"""
	Model for SimpleMovement.
	- finger
	- distance
	- time
	"""
	finger = models.CharField(
		max_length=50, 
		verbose_name='Finger', 
		choices=SIMPLE_CHOICES,
		default='Thumb finger',
        )
	
	distance = models.IntegerField(
    	verbose_name="Distance",
    	default=0,
    	validators=[
            MinValueValidator(0),
            MaxValueValidator(174)
		])
	time = models.DateTimeField(default=timezone.now)
	
	def __str__(self): 
		return '{0} {1} ({2})'.format(self.time, self.finger, self.distance )
   

@python_2_unicode_compatible
class CoordinatedMovement(models.Model):
	"""
	Model for CoordinatedMovement.
	- movement
	- distance
	- time
	"""
	movement = models.CharField(
		max_length=50, 
		verbose_name='Movement', 
		choices=COORDINATED_CHOICES,
		default='Take',
        )
	
	distance = models.IntegerField(
    	verbose_name="Distance",
    	default=0,
    	validators=[
            MinValueValidator(0),
            MaxValueValidator(174)
		])
	time = models.DateTimeField(default=timezone.now)
	
	def __str__(self): 
		return '{0} {1} ({2})'.format(self.time, self.movement, self.distance )


# @python_2_unicode_compatible
# class TemperatureBeforeMovement(models.Model):
# 	"""
# 	Model for Temperature Before SimpleMovement.
# 	- temperature
# 	- time
# 	"""

# 	temperature_before_movement = models.OneToOneField(
#         SimpleMovement,
#         on_delete=models.CASCADE,
#         primary_key=True,
#     )
# 	temperature = models.IntegerField(
# 		verbose_name="Temperature",
# 		validators=[
#             MinValueValidator(-150),
#             MaxValueValidator(150)
# 		])

# 	time = models.DateTimeField(default=timezone.now)

# 	def __str__(self):
# 		return 'Temperature before movement: {0} °C for {1}'.format(self.temperature, self.temperature_before_movement.movement)


@python_2_unicode_compatible
class Message(models.Model):
	"""
	Model for Message.
	- msg
	- text
	- time
	"""

	msg = models.CharField(max_length=50, verbose_name='Message')
	text = models.TextField()
	time = models.DateTimeField(default=timezone.now)
        
	def __str__(self):
   		return '{0} | {1} - {2}'.format(self.time, self.msg, self.text )



@python_2_unicode_compatible
class PostRequest(models.Model):
    """ Model request that are stored by middleware
        :param str text: includes id and 100 request symbol

    """
    request = models.TextField()

    def __str__(self):
        text = '{}: {}'.format(self.id, "%.100s" % self.request)
        return text

robotics/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from .models import CoordinatedMovement, SimpleMovement


class SimpleMovementForm(forms.ModelForm):
	
	class Meta():
		
		model = SimpleMovement
		fields = ['finger','distance',]
		widgets = {
			'finger': forms.Select(
				
				attrs={
				'style':"padding: 10px 55px; font-family: 'Open Sans', sans-serif; font-size: 1.5em; ",
				}),

			'distance': forms.TextInput( 
				attrs={
				'style':"margin-top: 20px; width: 23px; float:right; text-align: center; ",
			 	'value':"0", 
			 	'type':"text1", 
			 	'id':"text1",}),
 			}


class CoordinatedMovementForm(forms.ModelForm):
	
	class Meta():
		
		model = CoordinatedMovement
		fields = ['movement','distance',]
		widgets = {
			'movement': forms.Select(
				
				attrs={
				'style':" padding: 10px 55px; font-family: 'Open Sans', sans-serif;  font-size: 1.5em;",}),

			'distance': forms.TextInput( attrs={
				'style':"margin-top: 20px; width: 23px; float:right; text-align: center;",
			 	'value':"0", 
			 	'type':"text1", 
			 	'id':"text1",}),
 			}

robotics/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.db import connection
from django.views.generic import ListView, CreateView
from django.http import HttpResponseRedirect

from .models import PostRequest, SimpleMovement, CoordinatedMovement
from .forms import SimpleMovementForm, CoordinatedMovementForm


class List(ListView):
    
    context_object_name = 'list'
    queryset = PostRequest.objects.order_by('-id')[0:30]


class Simple(CreateView):

	model = SimpleMovement
	form_class = SimpleMovementForm
	success_url= '/control/simple/'

	def form_valid(self, form):

		if 'def' in self.request.POST: 
			# <input type="submit" name="def" value="Default" >
			SimpleMovement.objects.create(
				finger = self.request.POST['finger'],
				distance = 0,
				)
			
		elif 'ok' in self.request.POST: 
			# <input type="submit" name="ok" value="Default" >
			SimpleMovement.objects.create(
				finger = self.request.POST['finger'],
				distance=self.request.POST['distance'],
				)
			
		return HttpResponseRedirect(self.success_url)

		
class Coordinated(CreateView):

	model = CoordinatedMovement
	form_class = CoordinatedMovementForm
	success_url= '/control/coordinated/'

	def form_valid(self, form):

		if 'def' in self.request.POST:
			# <input type="submit" name="def" value="Default" >
			CoordinatedMovement.objects.create(
				finger = self.request.POST['movement'],
				distance = 0,
				)
			
		elif 'ok' in self.request.POST: 
			# <input type="submit" name="ok" value="Default" >
			CoordinatedMovement.objects.create(
				finger = self.request.POST['movement'],
				distance=self.request.POST['distance'],
				)
			
		return HttpResponseRedirect(self.success_url)

robotics/templates/robotics/about-us.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div id="banner">
	
	<div id="featured" style="padding: 0px 0px;"  class="container">
		<h2 class="title">About Us</h2>
		<div id="fbox1"> <img src="{% static 'images/pic04.jpg' %}" width="235" height="235" alt="" />
			<h2>Evheniia Monastyrna</h2>
			<p>In posuere eleifend quisque semper augue mattis wisi maecenas ligula.</p>
		</div>
		<div id="fbox2"> <img src="{% static 'images/pic05.jpg' %}" width="235" height="235" alt="" />
			<h2>Galina Neschadina</h2>
			<p>Maecenas ligula. Pellentesque viverra vulputate Aliquam erat volutpat.</p>
		</div>
		<div id="fbox3"> <img src="{% static 'images/pic06.jpg' %}" width="235" height="235" alt="" />
			<h2>Illya Bereza</h2>
			<p>Donec fermentum nibh in augue a lacus at urna congue rutrum.</p>
		</div>
		<div id="fbox4"> <img src="{% static 'images/pic07.png' %}" width="235" height="235" alt="" />
			<h2>Alexey Repkin</h2>
			<p>Suspendisse sit amet tellus eros bibendum volutpat nulla.</p>
		</div>
	</div>
</div>
{% endblock content %}

robotics/templates/robotics/all_fingers.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div id="banner"> 
   
	<div id="featured" style="padding: 0px 0px;" class="container" >

	    <h2 class="title">Choose the movement</h2>
	    <div id="sidebar">
			<div>
				<h2>Specification</h2>
				<ul class="style1">
					<li class="first">
						<p>Our robot can move maximum of 175 steps.</p>
						</li>
					<li>
						<p>Our criteria for the robot  to  check  the  temperature  and  comes  back  to  original  position  only  when  it  hits something  of  high  or  low  value  than  normal  range,  was  not  fulfilled.</p>
						 </li>
				</ul>
			</div>
		</div>
	    <ul id="menu1">
	    	<div id="page"  style="padding-bottom: 10px; padding-top: 10px; ">
				<div id="content"> 
					<form oninput="sizePic1()" action="" method="post">{% csrf_token %}
						<div style="margin-top: 10px; ">
							<div style="float:left; margin-right: 3em;"> 
							<li>
								<span>
							<!--<h2 style="cursor: pointer; text-align: left; font-size: 2em; padding: 5px 0px 20px; text-transform: capitalize;"></h2>-->
								<label >{{form.movement}}</label>
								</span>
							   
							</li>
							</div>
							<div style="float:left;margin-top: 10px; margin-bottom: 10px; ">
								<li>
									<p style="font-size: 1.5em; color: #009688;" for="your_name">Compression / decompression ratio: </p>
									<input style="margin-top: 20px; width: 300px;" type="range" id="slider1" value="0" min="0" max="174" step="1" onchange="showSliderValue1()">
									{{form.distance}}
							   	</li>
								<div style="margin-top: 20px;  float:right; margin-bottom: 10px;">
									<div style="float:left; margin-right: 1em;">
										<li >
											<input type="submit" name="def" value="Default" >
										</li>
									</div>  		
									<div style="float:right; "> 
										<li>
											<input type="submit" name="ok" value="OK" >
										</li>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</ul>
					
		</div>
	
</div>
{% endblock content %}

robotics/templates/robotics/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Smart Robotics</title>
<meta name="keywords" content="" />
<meta name="description" content="" />

  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 


<script src="{% static 'jquery-1.7.1.min.js' %}"></script>

<link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all" />

<script type="text/javascript" src="{% static 'jquery.slidertron-1.1.js' %}"></script>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600|Archivo+Narrow:400,700" rel="stylesheet" type="text/css" />
<script>
   function sizePic1() {
    size = document.getElementById("size1").value;
   
  }

</script>
<script >
	function showSliderValue1() {
		var sliderValue = document.getElementById("slider1").value;
		var text = document.getElementById("text1");
		text.value = sliderValue;
}
</script>


</head>
<body>
<div id="header-wrapper" >
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="{%url 'robotics:home' %}">Smart Group</a></h1>
		</div>
		<div id="menu">
			<ul id="navbar">
				<li class="first active"><a class="buttonText" id="button2" href="{%url 'robotics:home' %}" accesskey="1" title="">Homepage</a></li>
				<li><a type="button" href="{% url 'robotics:control' %}" accesskey="2" title="">Control</a></li>
				<li><a href="{% url 'robotics:about-us' %}" accesskey="3" title="">About Us</a></li>
				<li><a href="{% url 'robotics:contact-us' %}" accesskey="4" title="">Contact Us</a></li>
				<li><a href="{% url 'robotics:list' %}" accesskey="5" title="Latest requests.">Requests</a></li>
				
				
			</ul>
		</div>
	</div>
</div>
{% block content %}
	

<div id="banner">
<div id="featured" style="padding: 0px 0px;" class="container">
				<h2 class="title">Labor of love</h2>
			
	<div id="slider">
		<div class="viewer">
			<div class="reel">
			
				<div class="slide">
					<a class="link" href="#">Full story ...</a> <img src="{% static 'images/pic01.jpg' %}" alt="hgh" /> </div>
				<div class="slide">
					<a class="link" href="#">Full story ...</a> <img src="{% static 'images/pic02.jpg' %}" alt="" /> </div>
			</div>
		</div>
		<div class="indicator">
			<ul>
				<li class="active">1</li>
				<li>2</li>
			</ul>
		</div>
	</div>
	<script type="text/javascript">
		$('#slider').slidertron({
			viewerSelector: '.viewer',
			reelSelector: '.viewer .reel',
			slidesSelector: '.viewer .reel .slide',
			advanceDelay: 3000,
			speed: 'slow',
			navPreviousSelector: '.previous-button',
			navNextSelector: '.next-button',
			indicatorSelector: '.indicator ul li',
			slideLinkSelector: '.link'
		});
	</script> 
</div></div>

{% endblock content %}
<div id="footer" style="background: rgb(0, 150, 136) none repeat scroll 0% 0%;">
	<p>All rights reserved © 2017.  Photos by <a href="https://vk.com/donntu_fknt">Group</a>.</p>
</div>
<script type="text/javascript">
	$(document).ready(function() {
	$("#menu1 ul").hide();
	$("#menu1 li span").click(function() {
    $("#menu1 ul:visible").slideUp("normal");
    if (($(this).next().is("ul")) && (!$(this).next().is(":visible"))) {
        $(this).next().slideDown("normal");
    }
	});
	});
</script>

</body>
</html>

robotics/templates/robotics/contact-us.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div id="banner">
	<div id="featured" style="padding: 0px 0px;"  class="container">
		<h2 class="title">Contact Us</h2>
	<div id="page"  >
		<div id="content"> <img src="{% static 'images/pic04.jpg' %}" width="235" height="235" alt="" />
			<h2>Evheniia Monastyrna</h2>
			<p>In posuere eleifend quisque semper augue mattis wisi maecenas ligula.</p>
		</div>
		<div id="sidebar">
			<div>
				<h2>Categories</h2>
				<ul class="style1">
					<li class="first">
						<p><a href="#">Ipsum ante vivamus semper faucibus varius. Nam risus nibh, commodo vulputate.</a></p>
						</li>
					<li>
						<p><a href="#">Sed amet consequat lorem ipsum dolor sit amet blandit feugiat lorem ipsum sed ante nibh.</a></p>
						 </li>
				</ul>
			</div>
		</div>
	</div>
	<div id="page" >
		<div id="content"> <img src="{% static 'images/pic05.jpg' %}" width="235" height="235" alt="" />
			<h2>Galina Neschadina</h2>
			<p>In posuere eleifend quisque semper augue mattis wisi maecenas ligula.</p>
		</div>
		<div id="sidebar">
			<div>
				<h2>Categories</h2>
				<ul class="style1">
					<li class="first">
						<p><a href="#">Ipsum ante vivamus semper faucibus varius. Nam risus nibh, commodo vulputate.</a></p>
						</li>
					<li>
						<p><a href="#">Sed amet consequat lorem ipsum dolor sit amet blandit feugiat lorem ipsum sed ante nibh.</a></p>
						 </li>
				</ul>
			</div>
		</div>
	</div>
	<div id="page">
		<div id="content"> <img src="{% static 'images/pic06.jpg' %}" width="235" height="235" alt="" />
			<h2>Illya Bereza</h2>
			<p>In posuere eleifend quisque semper augue mattis wisi maecenas ligula.</p>
		</div>
		<div id="sidebar">
			<div>
				<h2>Categories</h2>
				<ul class="style1">
					<li class="first">
						<p><a href="#">Ipsum ante vivamus semper faucibus varius. Nam risus nibh, commodo vulputate.</a></p>
						 </li>
					<li>
						<p><a href="#">Sed amet consequat lorem ipsum dolor sit amet blandit feugiat lorem ipsum sed ante nibh.</a></p>
						 </li>
				</ul>
			</div>
		</div>
	</div>
	<div id="page" >
		<div id="content"> <img src="{% static 'images/pic07.png' %}" width="235" height="235" alt="" />
			<h2>Alexey Repkin</h2>
			<p>In posuere eleifend quisque semper augue mattis wisi maecenas ligula.</p>
		</div>
		<div id="sidebar">
			<div>
				<h2>Categories</h2>
				<ul class="style1">
					<li class="first">
						<p><a href="#">Ipsum ante vivamus semper faucibus varius. Nam risus nibh, commodo vulputate.</a></p>
						 </li>
					<li>
						<p><a href="#">Sed amet consequat lorem ipsum dolor sit amet blandit feugiat lorem ipsum sed ante nibh.</a></p>
						</li>
				</ul>
			</div>
		</div>
	</div></div>
</div>
{% endblock content %}

robotics/templates/robotics/control.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}

{% block content %} 
<div id="banner">     
	<div id="featured" style="padding: 0px 0px;" class="container">
	    <h2 class="title">Choose the movement</h2>
	    <div id="sidebar">
			<div>
				<h2>Specification</h2>
				<ul class="style1">
					<li class="first">
						<p><a href="#">Ipsum ante vivamus semper faucibus varius. Nam risus nibh, commodo vulputate.</a></p>
						</li>
					<li>
						<p><a href="#">Sed amet consequat lorem ipsum dolor sit amet blandit feugiat lorem ipsum sed ante nibh.</a></p>
						 </li>
				</ul>
			</div>
		</div>

			<div id="page" style="padding-bottom: 50px; width: 300px;">
				<div id="content"> 
					<a href="{%url 'robotics:simple' %}" title="Manage each individual finger.">
						<img src="{% static 'images/one.ico' %}" width="35" height="35" alt="" />
							<h2 style="text-align: left; font-size: 2em; padding: 5px 0px 20px; text-transform: capitalize;">Simple</h2></a>
							
				</div>	
			</div>
			<div id="page"   style="padding: 0px 0px 0px 0px; width: 300px;">
				<div id="content"> 
					<a title="Control synchronously with all fingers." href="{%url 'robotics:all-fingers' %}">
						<img src="{% static 'images/all.ico' %}" width="35" height="35" alt="" />
							<h2 style="text-align: left; font-size: 2em; padding: 5px 0px 20px; text-transform: capitalize;">Coordinated</h2></a>
							
				</div>	
			</div>
	</div>
</div>
{% endblock content %}

robotics/templates/robotics/fingers.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}

{% block content %} 
<div id="banner">     
	<div id="featured" class="container">
	    <h2 class="title">Choose the finfer</h2>
	    <div id="sidebar">
			<div>
				<h2>Specification</h2>
				<ul class="style1">
					<li class="first">
						<p>Our robot can move maximum of 175 steps.</p>
						</li>
					<li>
						<p>Our criteria for the robot  to  check  the  temperature  and  comes  back  to  original  position  only  when  it  hits something  of  high  or  low  value  than  normal  range,  was  not  fulfilled.</p>
						 </li>
				</ul>
			</div>
		</div>
	    <ul id="menu1">
	    	<div id="page"  style="padding-bottom: 10px; padding-top: 10px; ">
				<div id="content"> 
					<form oninput="sizePic1()" action="" method="post">{% csrf_token %}
						<div style="margin-top: 10px; ">
							<div style="float:left; margin-right: 3em;"> 
							<li>
								<span>
							<!--<h2 style="cursor: pointer; text-align: left; font-size: 2em; padding: 5px 0px 20px; text-transform: capitalize;"></h2>-->
								<label >{{form.finger}}</label>
								</span>
							   
							</li>
							</div>
							<div style="float:left;margin-top: 10px; margin-bottom: 10px; ">
								<li>
									<p style="font-size: 1.5em; color: #009688;" for="your_name">Compression / decompression ratio: </p>
									<input style="margin-top: 20px; width: 300px;" type="range" id="slider1" value="0" min="0" max="174" step="1" onchange="showSliderValue1()">
									{{form.distance}}
							   	</li>
								<div style="margin-top: 20px;  float:right; margin-bottom: 10px;">
									<div style="float:left; margin-right: 1em;">
										<li >
											<input type="submit" name="def" value="Default" >
										</li>
									</div>  		
									<div style="float:right; "> 
										<li>
											<input type="submit" name="ok" value="OK" >
										</li>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</ul>
	</div>	
</div>
{% endblock content %}

robotics/templates/robotics/requests.html
{% extends 'robotics/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}
<div id="banner">     
	<div id="featured" style="padding: 0px 0px;" class="container">
	    <h2 class="title">Requests</h2>

        {% for i in list %}
         <p style="text-align: left;">{{ i }}</p>
        {% endfor %}
</div></div>
{% endblock %}